import { Card, CardContent, CardHeader, CardTitle } from "@midday/ui/card";
import Link from "next/link";
import { MarkAllNotificationsReadButton, MarkNotificationReadButton } from "@/components/edms/notification-actions";
import { EdmsStatusBadge, formatEdmsLabel } from "@/components/edms/status-badge";
import { getEdmsNotificationFeed } from "@/lib/edms/notification-feed";
import { getRequiredDashboardSessionUser } from "@/lib/edms/session";

export default async function NotificationsPage() {
  const sessionUser = await getRequiredDashboardSessionUser();
  const notifications = await getEdmsNotificationFeed(sessionUser, 50);

  return (
    <div className="space-y-6 pt-6">
      <section className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div className="max-w-3xl space-y-3">
          <div className="space-y-2">
            <h1 className="text-3xl font-semibold tracking-tight md:text-4xl">
              Activities
            </h1>
            <p className="text-sm leading-6 text-muted-foreground md:text-base">
              Review requests, transmittals, and approval decisions generated by the EDMS workflow.
            </p>
          </div>
        </div>
        <MarkAllNotificationsReadButton disabled={notifications.every((item) => item.isRead)} />
      </section>

      <Card className="border-border bg-card shadow-sm">
        <CardHeader>
          <CardTitle>All notifications</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {notifications.length === 0 ? (
            <p className="text-sm text-muted-foreground">No notifications available.</p>
          ) : (
            notifications.map((notification) => (
              <div key={notification.id} className="group cursor-pointer border border-border bg-card p-4 transition-all hover:bg-accent hover:shadow-md">
                <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                  <div className="space-y-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="font-medium group-hover:text-primary">{notification.title}</p>
                      {!notification.isRead ? <EdmsStatusBadge status="unread" /> : null}
                    </div>
                    <p className="text-sm leading-6 text-muted-foreground">{notification.message}</p>
                    <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                      <span>{formatEdmsLabel(notification.type)}</span>
                      {notification.projectName ? <span>{notification.projectName}</span> : null}
                      <span>{notification.createdLabel}</span>
                    </div>
                    {notification.actionUrl ? (
                      <Link href={notification.actionUrl} className="text-sm text-primary hover:underline">
                        Open related item
                      </Link>
                    ) : null}
                  </div>
                  <MarkNotificationReadButton
                    notificationId={notification.id}
                    disabled={notification.isRead}
                  />
                </div>
              </div>
            ))
          )}
        </CardContent>
      </Card>
    </div>
  );
}